# Generated by Django 6.0.1 on 2026-01-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='coingecko_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
