# Generated by Django 6.0.1 on 2026-01-15 11:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_asset_coingecko_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='market.asset')),
            ],
        ),
    ]
